version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  php-fpm:
    image: php:8.1-fpm-alpine
    hostname: php-fpm
    volumes:
      - "./:/var/www/"
    working_dir: "/var/www/"
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:rw
      - ./:/var/www/
    ports:
      - "80:80"
    depends_on:
      - php-fpm



###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
